# Generated by Django 5.1.1 on 2024-11-04 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('license_plate', models.CharField(max_length=15)),
                ('vehicle_type', models.CharField(choices=[('bus', 'Bus'), ('truck', 'Truck'), ('van', 'Van'), ('car', 'Car')], max_length=20)),
                ('current_status', models.CharField(choices=[('available', 'Available'), ('in_use', 'In Use'), ('maintenance', 'Under Maintenance')], max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('contact_info', models.CharField(max_length=100)),
            ],
        ),
    ]
