# Generated by Django 5.1.1 on 2024-11-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shelters',
            fields=[
                ('camp_id', models.AutoField(primary_key=True, serialize=False)),
                ('camp_address', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField()),
                ('contact', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=6)),
            ],
        ),
    ]
