# Generated by Django 5.1.1 on 2024-11-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_shelters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportation',
            name='location',
            field=models.CharField(default='xxx', max_length=100),
        ),
    ]
