# Generated by Django 5.1.1 on 2024-11-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_transportation_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='transportation',
            name='current_status',
            field=models.CharField(choices=[('available', 'Available'), ('in use', 'In Use'), ('maintenance', 'Under Maintenance')], max_length=20),
        ),
    ]
